services:
  front:
    build:
      context: ./front
    container_name: front
    ports:
      - "8080:8080"
    networks:
      - my_network
    volumes:
      - ./front:/app
    environment:
      - API_URL=http://api-server:3000
      - STREAMER_URL=http://streamer:4000
      - DASHER_URL=http://dasher:5000

  api:
    build:
      context: ./api
    container_name: api-server
    ports:
      - "3000:3000"
    networks:
      - my_network
    volumes:
      - ./config.json:/app/config.json:ro  
      - ./api:/app
    environment:
      - DATABASE_URL=postgres://postgres:1234@postgres:5432/zoom?sslmode=disable

  streamer:
    build:
      context: ./streamer
    container_name: streamer
    ports:
      - "4000:4000"
    networks:
      - my_network
    volumes:
      - ./streamer:/app
    environment:
      - DASHER_URL=http://dasher:5000
  
  dasher:
    build:
      context: ./dasher
    container_name: dasher
    ports:
      - "5000:5000"
    networks:
      - my_network
    volumes:
      - ./dasher:/app
  
  database:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: zoom
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
